export const PROVIDER_CAPABILITIES = {
  polygon: {
    realtimeTicks: true,
    delayedTicks: false,
    candles: true,
    quotes: true,
    orderbook: true,
    forex: true,
    crypto: true,
    equity: true,
    index: true,
    futures: true,
    streaming: true,
    pollingFallback: false,
    requiresCredentials: true,
    requiresGateway: false,
    demoOnly: false,
  },
  ibkr: {
    realtimeTicks: true,
    delayedTicks: false,
    candles: true,
    quotes: true,
    orderbook: true,
    forex: true,
    crypto: false,
    equity: true,
    index: false,
    futures: true,
    streaming: true,
    pollingFallback: false,
    requiresCredentials: true,
    requiresGateway: true,
    demoOnly: false,
  },
  twelvedata: {
    realtimeTicks: false,
    delayedTicks: true,
    candles: true,
    quotes: true,
    orderbook: false,
    forex: true,
    crypto: true,
    equity: true,
    index: true,
    futures: false,
    streaming: false,
    pollingFallback: true,
    requiresCredentials: true,
    requiresGateway: false,
    demoOnly: false,
  },
  alphaVantage: {
    realtimeTicks: false,
    delayedTicks: true,
    candles: true,
    quotes: true,
    orderbook: false,
    forex: true,
    crypto: false,
    equity: true,
    index: false,
    futures: false,
    streaming: false,
    pollingFallback: true,
    requiresCredentials: true,
    requiresGateway: false,
    demoOnly: false,
  },
  yahoo: {
    realtimeTicks: false,
    delayedTicks: true,
    candles: true,
    quotes: true,
    orderbook: false,
    forex: true,
    crypto: true,
    equity: true,
    index: true,
    futures: false,
    streaming: false,
    pollingFallback: true,
    requiresCredentials: false,
    requiresGateway: false,
    demoOnly: false,
  },
  fallback_demo: {
    realtimeTicks: false,
    delayedTicks: false,
    candles: true,
    quotes: false,
    orderbook: true,
    forex: true,
    crypto: true,
    equity: true,
    index: true,
    futures: false,
    streaming: false,
    pollingFallback: false,
    requiresCredentials: false,
    requiresGateway: false,
    demoOnly: true,
  },
};

export const FAILOVER_PRIORITY = ['polygon', 'ibkr', 'twelvedata', 'alphaVantage', 'yahoo', 'fallback_demo'];

export function getCapabilities(providerId) {
  return PROVIDER_CAPABILITIES[String(providerId)] || {};
}

export function supportsAssetClass(providerId, assetClass) {
  const caps = PROVIDER_CAPABILITIES[String(providerId)];
  if (!caps) return false;
  if (caps.demoOnly) return true;
  return Boolean(caps[assetClass]);
}
