import mongoose from 'mongoose';
import { randomUUID } from 'node:crypto';
import { FeatureRecord } from './featureRecord.js';
import { quantPipelineEngine } from '../quant/quantPipelineEngine.js';
import { analysisHistoryStore } from '../history/analysisHistoryStore.js';
import { reversalDetectorEngine } from '../reversal/reversalDetectorEngine.js';
import { sessionContextEngine } from '../sessionContext/sessionContextEngine.js';
import { backtestEngine } from '../backtest/backtestEngine.js';
import { strategyValidationEngine } from '../validation/validationEngine.js';

class FeatureStore { constructor(){ this.memory=[]; } isMongoAvailable(){ return mongoose.connection?.readyState===1; } safeArray(v){ return Array.isArray(v)?v:[]; }
  normalize(record={}) { return { symbol:String(record.symbol||'').toUpperCase(), timeframe:String(record.timeframe||'1m'), timestamp:record.timestamp?new Date(record.timestamp):new Date(), sourceSnapshotId:String(record.sourceSnapshotId||''), alphaSignals:this.safeArray(record.alphaSignals), patternSignals:this.safeArray(record.patternSignals), strategyCandidates:this.safeArray(record.strategyCandidates), quantFeatures:this.safeArray(record.quantFeatures), qualityScores:this.safeArray(record.qualityScores), reversalPoints:this.safeArray(record.reversalPoints), sessionContext:record.sessionContext&&typeof record.sessionContext==='object'?record.sessionContext:{}, marketRegime:String(record.marketRegime||'unknown'), metadata:record.metadata&&typeof record.metadata==='object'?record.metadata:{}, createdAt:record.createdAt?new Date(record.createdAt):new Date() }; }
  toPublicShape(item){ return { id:String(item.id||item._id||randomUUID()), ...this.normalize(item), timestamp:new Date(item.timestamp||Date.now()).toISOString(), createdAt:new Date(item.createdAt||Date.now()).toISOString() }; }
  async buildFeatureRecord(symbol,timeframe='1m'){ const pipeline = quantPipelineEngine.runFullAnalysis(symbol,timeframe); const snapshot = await analysisHistoryStore.saveSnapshot(pipeline); const reversal = reversalDetectorEngine.detectReversals(symbol,timeframe); const sessionContext = sessionContextEngine.computeSessionContext(symbol,timeframe); const latestBacktest = backtestEngine.getBacktestResults(symbol).slice(-1)[0]||null; const latestValidation = strategyValidationEngine.getValidationResults(symbol).slice(-1)[0]||null; return { symbol,timeframe,timestamp:new Date(),sourceSnapshotId:snapshot?.id||'',alphaSignals:pipeline.alphaSignals,patternSignals:pipeline.patternSignals,strategyCandidates:pipeline.strategyCandidates,quantFeatures:pipeline.quantFeatures,qualityScores:pipeline.qualityScores,reversalPoints:reversal.reversalPoints,sessionContext,marketRegime:sessionContext.sessionBias||'unknown',metadata:{warnings:pipeline.warnings||[],dataSource:pipeline.dataSource||'unknown',isFallbackDemo:Boolean(pipeline.isFallbackDemo),backtestResult:latestBacktest,validationResult:latestValidation} }; }
  async saveFeatureRecord(record){ const normalized=this.normalize(record); if(this.isMongoAvailable()){ try{ const created=await FeatureRecord.create(normalized); return this.toPublicShape(created.toJSON()); } catch(err){ console.warn(`FeatureStore Mongo save failed, using in-memory fallback: ${err.message}`);} } const local={id:randomUUID(),...normalized}; this.memory.unshift(local); return this.toPublicShape(local); }
  async getFeatureRecords(symbol,limit=25){ const s=String(symbol||'').toUpperCase(); const l=Math.min(Math.max(Number(limit)||25,1),200); if(this.isMongoAvailable()){ try{ const items=await FeatureRecord.find(s?{symbol:s}:{}).sort({createdAt:-1}).limit(l).lean(); return items.map((i)=>this.toPublicShape(i)); } catch(err){ console.warn(`FeatureStore Mongo read failed, using in-memory fallback: ${err.message}`);} } return this.memory.filter((x)=>!s||x.symbol===s).slice(0,l).map((i)=>this.toPublicShape(i)); }
  async getFeatureRecordById(id){ const sid=String(id||''); if(!sid) return null; if(this.isMongoAvailable()&&mongoose.isValidObjectId(sid)){ const item=await FeatureRecord.findById(sid).lean(); if(item) return this.toPublicShape(item);} const local=this.memory.find((x)=>x.id===sid); return local?this.toPublicShape(local):null; }
  async clearFeatureRecords(symbol){ const s=String(symbol||'').toUpperCase(); if(this.isMongoAvailable()){ try{ const result=await FeatureRecord.deleteMany(s?{symbol:s}:{}); return {deleted:result.deletedCount||0}; } catch(err){ console.warn(`FeatureStore Mongo clear failed, using in-memory fallback: ${err.message}`);} } const before=this.memory.length; this.memory=s?this.memory.filter((x)=>x.symbol!==s):[]; return {deleted:before-this.memory.length}; }
}
export const featureStore = new FeatureStore();
